project:
  type: website
  title: "Big Data lecture slides"
  output-dir: docs
  resources: 
    - "chapters/chapter001/img"
    - "chapters/chapter002/img"
website: 
  title: "Big Data lecture slides"