project:
  type: website
  title: "Big Data lecture slides"
  # output-dir: docs
  resources: 
    - "chapters/chapter001/img"
    - "chapters/chapter002/img"
    - "chapters/chapter002/data"
    
execute: 
  echo: false
  warning: false
author:
  name: Prof. Dr. Tim Weber
  oricd: "000-0003-2931-8963"
  email: tim.weber@th-deg.de
  corresponding: true
  affiliations:
   - name: Deggendorf Institute of Technology
     address: Badstrasse 21, Germany
     department: Applied Natural Sciences and Industrial Engineering (NUW)
website: 
  title: "Big Data lecture slides"
  page-footer: "Copyright Prof. Dr. Tim Weber, 2024"
  sidebar: 
    style: "floating"
    search: true
    contents: 
      - section: Introduction
        text: "slides"
        href: chapters/chapter100/index.qmd
        contents: 
          - text: "Introductory exercises in R"
            href: https://mechtrix.github.io/BigData_exercises/get_started.html
      - section: Data Sources
        text: "slides"
        href: chapters/chapter200/index.qmd
        contents: 
          - text: "Data Sources exercises in R"
            href: https://mechtrix.github.io/BigData_exercises/data_sources.html
      - section: Data Quality
        text: "slides"
        href: chapters/chapter300/index.qmd
        contents: 
          - text: "Data Distribution exercises in R"
            href: https://mechtrix.github.io/BigData_exercises/data_distributions.html
          - text: "Gage R&R"
            href: https://mechtrix.github.io/BigData_exercises/gage_rr.html
      - section: Data Bias
        text: "slides"
        contents: 
          - text: "slides"
            href: chapters/chapter400/index.qmd
      - section: Data crunching
        contents: 
          - text: "Traditional Methods"
            href: chapters/chapter500_TraditionalMeasures/index.qmd
          - text: "Map Reduce"
            href: chapters/chapter510_MapReduce/index.qmd
          - text: "Gradient Descent"
            href: chapters/chapter520_GradientDescent/index.qmd
          - text: "Maximum Likelihood Estimation"
            href: chapters/chapter530_MLE/index.qmd
          - text: "Principal Component Analysis"
            href: chapters/chapter540_PCA/index.qmd
          - section: "Cluster Analysis"
            contents: 
              - href: chapters/chapter551_kNN/index.qmd
              - href: chapters/chapter552_kMeans/index.qmd
              - href: chapters/chapter553_pam/index.qmd
              - href: chapters/chapter554_dbscan/index.qmd
              - href: chapters/chapter555_agglomerative/index.qmd